#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export FASTLIO_ENV_SCRIPT="${SCRIPT_DIR}/env_fastlio_nx.sh"
export ROI_LIDAR_CORNER_PUBLISH_DEBUG_UV="${ROI_LIDAR_CORNER_PUBLISH_DEBUG_UV:-true}"
export ROI_LIDAR_CORNER_DEBUG_OVERLAY_FRAME_COUNT="${ROI_LIDAR_CORNER_DEBUG_OVERLAY_FRAME_COUNT:-1}"
export ROI_LIDAR_CORNER_SUBSCRIBE_CORNER3D_DEBUG="${ROI_LIDAR_CORNER_SUBSCRIBE_CORNER3D_DEBUG:-true}"
export ROI_LIDAR_CORNER_SUBSCRIBE_SOLVER_DEBUG_UV="${ROI_LIDAR_CORNER_SUBSCRIBE_SOLVER_DEBUG_UV:-true}"
export ROI_LIDAR_CORNER_ENABLE_DEBUG_MARKERS="${ROI_LIDAR_CORNER_ENABLE_DEBUG_MARKERS:-true}"
exec "${SCRIPT_DIR}/run_fastlio_with_roi.sh" "$@"
